// ============================================================
// lib.rs — Rust library entry point
// ============================================================

pub mod api;
pub mod config;
pub mod errors;
pub mod escpos_adapter;
pub mod printer;
pub mod transport;
mod jobs;

// Code generated by flutter_rust_bridge — DO NOT EDIT MANUALLY
#[allow(clippy::all)]
mod frb_generated;

/// Dummy function to force symbols to be exported on Windows for Cargokit.
#[no_mangle]
pub extern "C" fn thermal_printer_rs_rust_arc_increment_strong_count() {}

/// Initializes the structured logging system with tracing.
/// Call once at the start of the Flutter application.
pub fn init_logging() {
    use tracing_subscriber::{fmt, EnvFilter};
    let _ = fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .try_init();
}
