server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    autoindex on;
    autoindex_format html;

    location /output/ {
        alias /usr/share/nginx/html/output/;
        autoindex on;
        types {
            image/png  png;
            application/pdf pdf;
        }
    }

    location = / {
        return 301 /output/;
    }
}
