// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_dither_and_encode`, `build_config`, `err`, `ok`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Returns the current printer state as a synchronous snapshot.
/// Useful for polling or checking state before an operation.
PrinterStateDto getPrinterState() =>
    RustLib.instance.api.crateApiSimpleGetPrinterState();

/// Subscribes to the printer state stream (push model).
///
/// The `StreamSink` type here is the newtype generated by FRB's
/// `frb_generated_boilerplate_io!()` macro. Accessed via the private
/// `frb_generated` module. FRB codegen constructs this type and passes
/// it here automatically — do not call this function from Dart directly.
Stream<PrinterStateDto> createStateStream() =>
    RustLib.instance.api.crateApiSimpleCreateStateStream();

/// Initializes the print service.
Future<void> initPrinter({required PrinterConfigDto config}) =>
    RustLib.instance.api.crateApiSimpleInitPrinter(config: config);

/// Explicitly connects to the transport.
Future<void> connectPrinter() =>
    RustLib.instance.api.crateApiSimpleConnectPrinter();

/// Prints simple text.
Future<PrintResultDto> printText({required String text}) =>
    RustLib.instance.api.crateApiSimplePrintText(text: text);

/// Prints a complete receipt.
Future<PrintResultDto> printReceipt({
  required String title,
  required List<ReceiptLineDto> lines,
  required String total,
  String? qrData,
}) => RustLib.instance.api.crateApiSimplePrintReceipt(
  title: title,
  lines: lines,
  total: total,
  qrData: qrData,
);

/// Disconnects the transport and stops the worker.
Future<void> disconnectPrinter() =>
    RustLib.instance.api.crateApiSimpleDisconnectPrinter();

/// Drains all pending jobs in the background worker.
Future<void> clearPrintQueue() =>
    RustLib.instance.api.crateApiSimpleClearPrintQueue();

/// Sends raw bytes and awaits until the hardware confirms the write.
///
/// This is the blocking counterpart to [enqueue_write_bytes].
/// Use this when the caller needs to know the bytes were actually transmitted
/// before proceeding (e.g., before cutting paper or opening a drawer).
Future<void> writeRawBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSimpleWriteRawBytes(bytes: bytes);

/// Reads raw bytes from the transport.
/// Used for querying printer status via `DLE EOT`.
Future<Uint8List> readRawBytes({
  required int bytes,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiSimpleReadRawBytes(
  bytes: bytes,
  timeoutMs: timeoutMs,
);

/// Enqueues a raw bytes payload (fire-and-forget).
///
/// Returns immediately after placing the job in the background queue.
/// The bytes will be sent by the background worker — there is no
/// acknowledgement that the hardware has actually received them.
/// Use [write_raw_bytes] if you need confirmed delivery.
Future<void> enqueueWriteBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSimpleEnqueueWriteBytes(bytes: bytes);

/// Enqueues a text print job (non-blocking).
Future<void> enqueuePrintText({required String text}) =>
    RustLib.instance.api.crateApiSimpleEnqueuePrintText(text: text);

/// Enqueues a receipt print job (non-blocking).
Future<void> enqueuePrintReceipt({
  required String title,
  required List<ReceiptLineDto> lines,
  required String total,
  String? qrData,
}) => RustLib.instance.api.crateApiSimpleEnqueuePrintReceipt(
  title: title,
  lines: lines,
  total: total,
  qrData: qrData,
);

/// Encodes raw RGBA pixel data into an ESC/POS GS v 0 raster image command
/// using Floyd-Steinberg dithering.
///
/// The heavy computation is moved to Tokio's blocking thread pool so the
/// async executor (and therefore the Flutter UI) is never starved.
///
/// Returns the complete ESC/POS byte sequence, ready to send to the printer.
Future<Uint8List> encodeRasterImage({
  required List<int> rgba,
  required PlatformInt64 width,
  required PlatformInt64 height,
}) => RustLib.instance.api.crateApiSimpleEncodeRasterImage(
  rgba: rgba,
  width: width,
  height: height,
);

bool isPrinterReady() => RustLib.instance.api.crateApiSimpleIsPrinterReady();

/// Result of a print operation
class PrintResultDto {
  final bool success;
  final int bytesSent;
  final String? errorMessage;

  const PrintResultDto({
    required this.success,
    required this.bytesSent,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      success.hashCode ^ bytesSent.hashCode ^ errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrintResultDto &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          bytesSent == other.bytesSent &&
          errorMessage == other.errorMessage;
}

/// Printer configuration (passed from Dart)
class PrinterConfigDto {
  final TransportTypeDto transport;
  final String? host;
  final int? port;
  final int? vendorId;
  final int? productId;
  final String? bleAddress;
  final BigInt timeoutMs;
  final int paperWidth;
  final int maxRetries;

  const PrinterConfigDto({
    required this.transport,
    this.host,
    this.port,
    this.vendorId,
    this.productId,
    this.bleAddress,
    required this.timeoutMs,
    required this.paperWidth,
    required this.maxRetries,
  });

  static Future<PrinterConfigDto> default_() =>
      RustLib.instance.api.crateApiSimplePrinterConfigDtoDefault();

  @override
  int get hashCode =>
      transport.hashCode ^
      host.hashCode ^
      port.hashCode ^
      vendorId.hashCode ^
      productId.hashCode ^
      bleAddress.hashCode ^
      timeoutMs.hashCode ^
      paperWidth.hashCode ^
      maxRetries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrinterConfigDto &&
          runtimeType == other.runtimeType &&
          transport == other.transport &&
          host == other.host &&
          port == other.port &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          bleAddress == other.bleAddress &&
          timeoutMs == other.timeoutMs &&
          paperWidth == other.paperWidth &&
          maxRetries == other.maxRetries;
}

/// Printer state tracked by the background worker
enum PrinterStateDto { disconnected, connecting, connected, printing, error }

/// Receipt item (label + value/price)
class ReceiptLineDto {
  final String label;
  final String value;

  const ReceiptLineDto({required this.label, required this.value});

  @override
  int get hashCode => label.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiptLineDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value;
}

/// Transport type for connection
enum TransportTypeDto { tcp, usb, bluetooth }
